# Setup a linux box with R packages to run the aqi_watch.R script
# Submit an issue if a monitor is above 90 AQI

name: aqi_alert

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches:
  #    - main
      
  workflow_dispatch:
  
  # At every 13 minutes past the hour
  schedule:
      - cron:  '13 * * * *'  
    
jobs:
  site:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1'
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
          use-public-rspm: false
          
      - name: "[Stage] [Linux] Install required system libs"
        if: runner.os == 'Linux'
        run: sudo apt install libcurl4-openssl-dev libgit2-dev
        
      - name: "[Custom block] [Linux] Install spatial libraries"
        if: runner.os == 'Linux'
        run: sudo apt-get install libgdal-dev libproj-dev libgeos-dev libudunits2-dev    
        
      - uses: actions/cache@v3
        id: cache-renv
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore R packages from cache
        shell: Rscript {0}
        run: |
          install.packages("renv")
          renv::restore()

      - name: Get current AQI monitor results
        run: |
          source("R/aqi_watch.R")
        shell: Rscript {0} 

      - name: List files
        run: |
          ls
          
      - name: Check issue.md existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: issue.md

      - uses: JasonEtco/create-an-issue@v2
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: issue.md

      # Add new files in data and web folder, commit along with other modified files, push
      - name: Commit website updates
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git add web/*
          git add docs/*
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
